# Generated by Django 5.2.6 on 2025-09-19 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text="Contact's full name", max_length=200)),
                ('email', models.EmailField(help_text="Contact's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(help_text="Contact's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text="Contact's address", null=True)),
                ('country', models.CharField(blank=True, help_text="Contact's country", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the contact was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the contact was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the contact is active')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_contac_email_800caf_idx'), models.Index(fields=['fullname'], name='core_contac_fullnam_cf4ba1_idx'), models.Index(fields=['created_at'], name='core_contac_created_643cbb_idx')],
            },
        ),
    ]
