# Generated by Django 5.2.6 on 2025-09-19 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text="Contact's email address", max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
